//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        public int CommandeID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USER USER { get; set; }
    }
}
